### ISSUE TITLE
Calculating Grey Matter Volume using Eve atlas

### ISSUE THREAD

**Issue by kmarvel54** [muschellij2/Neurohacking#11] opened 2020-01-29 20:47 UTC
Hi Muschelli,

I have gone through your Neurohacking coursera program and I have learnt a lot. Thanks you.

I would like to calculate the grey matter volumes for specific regions of interest using  Eve atlas (JHU_MNI_SS_WMPM_Type-I.nii.gz). The steps are as follows:

I have written the R script, which I borrowed from your course, and is as follows:

library(oro.dicom) 
library(oro.dicom) 
library(oro.nifti) 
library(ANTsR) 
library(extrantsr)

Sys.getenv("FSLDIR")
library(fslr)
library(scales)
library(ggplot2)
library(reshape2)
library(plyr)

library(oro.dicom) 
library(oro.dicom) 
library(oro.nifti) 
library(ANTsR) 
library(extrantsr)

Sys.getenv("FSLDIR")
library(fslr)
library(scales)
library(ggplot2)
library(reshape2)
library(plyr)

## SyN registration
mi <- antsImageRead("c1T1.nii.gz", dimension=3) # c1T1.nii.gz is the grey matter volume
fi <- antsImageRead("MNI152_T1_1mm_brain.nii.gz", dimension=3)
mytx <- antsRegistration(fixed = fi, moving = mi, typeofTransform = c("SyN"))

## Read the atlas
atlas <- readNIfTI("JHU_MNI_SS_WMPM_Type-I.nii.gz", reorient=FALSE)

## Calculate regional grey matter volumes 
JHU_lut_df = read.table("JHU_MNI_SS_WMPM_Type-I_SlicerLUT.txt", stringsAsFactors=FALSE)
JHU_lut_df = JHU_lut_df[, 1:2]
colnames(JHU_lut_df) = c("index", "Label")
JHU_lut_df$index = as.numeric(JHU_lut_df$index)
JHU_lut_df[1:4,]

## Reading in the Atlas 
JHU.img = atlas

## Make a data frame with the index of the atlas and the value of the ROI at that voxel
roi.df = data.frame(index = JHU.img[grey_matter_volumes > 0], roi = grey_matter_volumes[grey_matter_volumes > 0])

## Obtain the number (sum) of voxels that have an roi value > 0 in the roi by the index of labels
label_sums = ddply(roi.df, .(index), summarize, sum_roi = sum(roi), sum_roi_thresh = sum(roi > 0))
label_sums = merge(label_sums, JHU_lut_df, by="index")

voxel_resolution = voxres(JHU.img, units="cm")  
label_sums$volume = label_sums$sum_roi_thresh * voxel_resolution

Is this script is ok since I am trying to compute grey matter volumes by summing in the 
c1T1.nii.gz segmentation maps with Eve atlas region then multiply by the volume of each voxel to convert the units in cm^3?

Thanks,
kate

**Comment by muschellij2** [comment] 2020-03-16 02:03
Closing this as it is a duplicate of https://github.com/ANTsX/ANTsR/issues/293

**Closed as completed by muschellij2** 2020-03-16 02:03 UTC
